name: repare_cycle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
    - dcor>=0.6
    - networkx>=3.4
    - scikit-learn>=1.6
    - scipy>=1.15
    - numpy>=2.0
    - matplotlib>=3.9
    - seaborn>=0.13
    - pandas>=2.2
    - sempler>=0.2.14
    - pytest>=8.3
    - snakemake>=9.0
    - snakefmt>=0.11
