include: "rules/synth.smk"
include: "rules/threshold.smk"
include: "rules/ablation.smk"
include: "rules/intervention.smk"
include: "rules/paper_revision.smk"


rule all:
    default_target: True
    input:
        expand(
            "results/synth_main_regime={regime}_density={density}.pdf",
            regime=synth_regimes, density=synth_densities,
        ),
        "results/synth_main_combined.pdf",
        "results/paper_fig3.pdf",
        "results/scalability_disjointcycles.pdf",
        "results/disjoint_micro.pdf",
        "results/synth_threshold.pdf",
        "results/sample_complexity.pdf",
